#\DeclareLyXModule{AcuteLyx}
#DescriptionBegin
# AcuteLyx module
# Commands will appear under Insert > Custom Inset (because of LyXType custom)
#DescriptionEnd
#
#Author: Amin Yahyaabadi <aminyahyaabadi74@gmail.com>


Preamble
% for subfigures/subtables
%\usepackage{ieeetrantools}

%Colon after year
%\DeclareDelimFormat[bib,biblist]{nametitledelim}{\addcolon\space}

%Year and parantheses in bold
 % <=========================== date

%% The new list's label is "New" and will be titled "The other list".
%% To put cites into this list, use \citeNew.
%\newcites{Fuzzy Theory}{The other list}
%\newcommand*{\doi}[1]{\href{http://dx.doi.org/#1}{doi: #1}}

EndPreamble

Style Abstract
  LatexName	Abstract
  Preamble
	\newenvironment{Abstract}{
		\chapter*{Abstract}
	}{
	}
  EndPreamble
  LatexType Environment
  LabelType		Above
  LabelString "Abstract"
  LabelFont
    Size Huge
  EndFont
End


Style ChapterAbstract
  LatexName	ChapterAbstract
  Preamble
	\newenvironment{ChapterAbstract}[1]{
		\begin{center}\normalfont\textbf{Abstract}\end{center}
		\begin{quotation}
	}{
		\end{quotation}
		\vspace{#1}
	}
  EndPreamble
  LatexType Environment
  Argument 1
	  LabelString	"vspace"
	  Mandatory	1
	  DefaultArg	"1cm"
	  AutoInsert	1
  EndArgument
End

